### ISSUE TITLE
Can I use this system?

### ISSUE THREAD

**Issue by elBandoler** [rash2kool/Online-Banking-system#6]
Hey,
Sorry for opening an issue but I found no other way to contact you.
I'd like to use the system for a micronational bank.
You can read about micronationalism over here: micronations.wiki
I promise not to use it for any illegal purposes and/or in any illegal way.
If you'd like me to present details as a guarantee, leave your mail and I will.

Thanks in advance,
elBandoler.

**Comment by elBandoler** [comment]
@g33kyrash more than six months, didn't get your answer yet...

**Comment by horllste** [comment]
what did you need exactly? contact me maybe i could help
horllste@gmail.com

**Comment by elBandoler** [comment]
> what did you need exactly? contact me maybe i could help
> [horllste@gmail.com](mailto:horllste@gmail.com)

I just need the creator's permission to use this system. He specified in the README.md that one needs his permission to use it.

**Comment by horllste** [comment]
you can use it, just dont use it for illegal purposes, thats what is stated in the READ
ME

**Comment by elBandoler** [comment]
> you can use it, just dont use it for illegal purposes, thats what is stated in the READ
> ME

Well, you're wrong. Here's a quote, literally the first line:

> **This project should not be modified in any way and used anywhere else without my permission.**

So nobody can use or modify it in ANY way without being granted permission from the creator. I intend to respect that, as there is no LICENSE.md or other kind of license.

**Comment by horllste** [comment]
ohh, sorry i dont see that, i have a copy of it that i use for learning purposes few years ago when i start developing with php

**Comment by g33kyrash** [comment]
Please feel free to use this for educative/learning purposes. That message was intended for scammers.

Apologies for the inconvenience caused.
